.\" '\"
.\" '\" Ivy, C interface \- library managing connexions to a software bus
.\" '\"
.\" '\" Copyright (C) 1997-1999
.\" 
.\" '\"
.\" '\" See the file "license.terms" for information on usage and redistribution
.\" '\" of this file, and for a DISCLAIMER OF ALL WARRANTIES.
.\" '\" 
.\" '\" 
.\" '\"	# Start an argument description
.\" .de AP
.\" .ie !"\\$4"" .TP \\$4
.\" .el \{\
.\" .   ie !"\\$2"" .TP \\n()Cu
.\" .   el          .TP 15
.\" .\}
.\" .ie !"\\$3"" \{\
.\" .ta \\n()Au \\n()Bu
.\" \&\\$1	\\fI\\$2\\fP	(\\$3)
.\" 
.\" .\}
.\" .el \{\
.\" .br
.\" .ie !"\\$2"" \{\
.\" \&\\$1	\\fI\\$2\\fP
.\" .\}
.\" .el \{\
.\" \&\\fI\\$1\\fP
.\" .\}
.\" .\}
.\" ..
.\" '\"	# define tabbing values for .AP
.\" .de AS
.\" .nr )A 10n
.\" .if !"\\$1"" .nr )A \\w'\\$1'u+3n
.\" .nr )B \\n()Au+15n
.\" 
.\" .if !"\\$2"" .nr )B \\w'\\$2'u+\\n()Au+3n
.\" .nr )C \\n()Bu+\\w'(in/out)'u+2n
.\" ..
.\" '\"	# BS - start boxed text
.\" '\"	# ^y = starting y location
.\" '\"	# ^b = 1
.TH "Ivy-c-3.11" "1" "3.11" "Francois-Regis Colin, Stephane Chatty" "library"
.SH "NAME"
ivy\-c \- a software bus library
.SH "SYNOPSIS"
Ivy\-c provides a useful set of C library functions for communicating between different
processes through a software bus
.SH "DESCRIPTION"
Ivy is a software bus, ie a system that allows any software component to freely exchange data.
The basic principle of a software bus is to ease the rapid implementation of new agents, and to manage a dynamic collection of agents on the bus: agents connect, send and receive messages, and disconnect without perturbing the overall functionment of the bus.
Each time an application initializes a connection on the bus, a
"ready" message is sent to all other applications already connected, and the
list of the messages subscribed by this application is dispatched.
The format for the messages is free.
.nf 
The essential functions of Ivy are:
.nf 
.I Connexion
.nf 
.I Message subscription
.nf 
.I Main loop
.nf 
.I  Message sending
.SH "FILES"
.I /usr/include/ivy.h
.nf 
.I /usr/include/ivyloop.h
.nf 
.I /usr/include/ivysocket.h
.SH "ENVIRONMENT"
\fIIVYBUS\fR ipv4 network adress xxx.xxx.xxx.xxx\fB:\fRport number example : 127.255.255.255:2000
.nf 

.SH "DIAGNOSTICS"
error messages displayed
.SH "BUGS"
none reported yet!
.SH "AUTHORS"
.nf 
Francois\-Regis Colin
.nf 
Stephane Chatty
.SH "SEE ALSO"
ivyprobe (1)
ivy\-c\-functions (1)
.sp
For further details, please refer to the Ivy html page at http://www.tls.cena.fr/products/ivy/
.SH "NOTES"
In case of any comment or bug report on this library, please contact
ivy@tls.cena.fr

